### ISSUE TITLE
Security and build issues.

### ISSUE THREAD

**Issue by ApzSK** [gree/unity-webview#1016]
Hi, I've been working with this library for about a week now and there is one security issue, that keeps showing in our internal tests - WebView debugging is always enabled, even if app is built as a release it keeps showing up the logs. I've tried to change the flags but no success.

So i decided to remove this one line (image) and re-compile the project.
![image](https://github.com/gree/unity-webview/assets/59923458/e9764a1b-1fa7-4aaa-8fa7-06cff5fc3f65)

Sadly I've run into issues - after installing older Unity and Android SDK I've had a lot of issues during compilation like:
```
`User
Execution failed for task ':webview:processDebugAndroidTestManifest'.
> Unable to make field private final java.lang.String java.io.File.path accessible: module java.base does not "opens java.io" to unnamed module @78ceed1`
```
and
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':webview:parseReleaseLocalResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > !directory.isDirectory()
```

After many hours I've upgraded gradle, set (correct?) java and compile, I have **webview-release.aar** file generated in _.../unity-webview\plugins\build\Packager\Assets\Plugins\Android_ and when i copy it to my Unity project and run i get this issue:

```
AndroidJavaException: java.lang.NoSuchMethodError: no non-static method with name='Init' signature='(Ljava/lang/String;ZZILjava/lang/String;)V' in class Ljava.lang.Object;
                                                                                                    java.lang.NoSuchMethodError: no non-static method with name='Init' signature='(Ljava/lang/String;ZZILjava/lang/String;)V' in class Ljava.lang.Object;
                                                                                                    	at com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source:226)
                                                                                                    	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
                                                                                                    	at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
                                                                                                    	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
                                                                                                      at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 
                                                                                                      at UnityEngine.AndroidJNISafe.CallStaticObjectMethod (System.IntPtr clazz, System.IntPtr methodID, UnityEngine.jvalue[
```

Do i miss any build step? Can anyone help me to set this up correctly? Which Java version should I use? If possible can anyone build .aar file without this one line on the image, so it would work?

I'm using Windows 11, and instructions for the build are unclear for me, and probably obsolete

Thanks for your help in advance

**Comment by KojiNakamaru** [comment]
In #1017, I modified the build process to emit release/development WebViewPlugin.aar depending on EditorUserBuildSettings.development. The release version of WebViewPlugin.aar doesn't contain setWebContentsDebuggingEnabled so it should be okay for your requirement. Could you please try the latest binaries.

I'll later update README.md about how to build WebViewPlugin.aar.
