### ISSUE TITLE
Unity AndroidJavaException: java.lang.ClassNotFoundException: net.gree.unitywebview.CWebViewPlugin

### ISSUE THREAD

**Issue by Camper-code** [gree/unity-webview#1027]
Unity: 2022.3.12f1
Platform: Android
Builded from: MacOS
Exception type: Build only
Represent:
1) installing unity-web by package manager
2) trying to call Init() method

2023/12/23 00:29:05.744 31590 31626 Error Unity AndroidJavaException: java.lang.ClassNotFoundException: net.gree.unitywebview.CWebViewPlugin
2023/12/23 00:29:48.885 32070 32098 Error Unity AndroidJavaException: java.lang.ClassNotFoundException: net.gree.unitywebview.CWebViewPlugin
2023/12/23 00:29:48.885 32070 32098 Error Unity java.lang.ClassNotFoundException: net.gree.unitywebview.CWebViewPlugin
2023/12/23 00:29:48.885 32070 32098 Error Unity 	at java.lang.Class.classForName(Native Method)
2023/12/23 00:29:48.885 32070 32098 Error Unity 	at java.lang.Class.forName(Class.java:454)
2023/12/23 00:29:48.885 32070 32098 Error Unity 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
2023/12/23 00:29:48.885 32070 32098 Error Unity 	at com.unity3d.player.UnityPlayer.-$$Nest$mnativeRender(Unknown Source:0)
2023/12/23 00:29:48.885 32070 32098 Error Unity 	at com.unity3d.player.UnityPlayer$F$a.handleMessage(Unknown Source:122)
2023/12/23 00:29:48.885 32070 32098 Error Unity 	at android.os.Handler.dispatchMessage(Handler.java:103)
2023/12/23 00:29:48.885 32070 32098 Error Unity 	at android.os.Looper.loop(Looper.java:224)
2023/12/23 00:29:48.885 32070 32098 Error Unity 	at com.unity3d.player.UnityPlayer$F.run(Unknown Source:24)
2023/12/23 00:29:48.885 32070 32098 Error Unity Caused by: java.lang.ClassNotFoundException: Didn't find class "net.gree.unitywebview.CWebViewPlugin" on path: DexPathList[[zip file "/data/app/com.campstudio.test-W5xn88YD7Jt2D6p1xyxfog==/base.apk"],nativeLibraryDirectories=[/data/app/com.campstudio.test-W5xn88YD7Jt2D6p1xyxfog==/lib/arm64, /data/app/com.campstudio.test-W5xn88YD7Jt2D6p1xyxfog==/base.apk!/lib/arm64-v8a, /system/lib64, /product

**Comment by KojiNakamaru** [comment]
Thank you for the report. I fixed the issue in #1028 and updated binaries. Could you please try the latest.
