### ISSUE TITLE
Unity2022.3.22f1でandroidbuildしたときに正常に動かない

### ISSUE THREAD

**Issue by omochi0619** [gree/unity-webview#1060]
androidでbuildをしたときに正常に画面に表示されない問題が出ていて解決策がわからずに困っているのですが何に問題がありますでしょうか
以下エラー文になります。

2024/03/27 16:34:49.093 31512 31541 Error Unity AndroidJavaException: java.lang.ClassNotFoundException: net.gree.unitywebview.CWebViewPlugin

2024/03/27 16:34:49.093 31512 31541 Error Unity java.lang.ClassNotFoundException: net.gree.unitywebview.CWebViewPlugin

2024/03/27 16:34:49.093 31512 31541 Error Unity 	at java.lang.Class.classForName(Native Method)

2024/03/27 16:34:49.093 31512 31541 Error Unity 	at java.lang.Class.forName(Class.java:536)

2024/03/27 16:34:49.093 31512 31541 Error Unity 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)

2024/03/27 16:34:49.093 31512 31541 Error Unity 	at com.unity3d.player.UnityPlayer.-$$Nest$mnativeRender(Unknown Source:0)

2024/03/27 16:34:49.093 31512 31541 Error Unity 	at com.unity3d.player.UnityPlayer$F$a.handleMessage(Unknown Source:122)

2024/03/27 16:34:49.093 31512 31541 Error Unity 	at android.os.Handler.dispatchMessage(Handler.java:102)

2024/03/27 16:34:49.093 31512 31541 Error Unity 	at android.os.Looper.loopOnce(Looper.java:201)

2024/03/27 16:34:49.093 31512 31541 Error Unity 	at android.os.Looper.loop(Looper.java:288)

2024/03/27 16:34:49.093 31512 31541 Error Unity 	at com.unity3d.player.UnityPlayer$F.run(Unknown Source:24)

2024/03/27 16:34:49.093 31512 31541 Error Unity Caused by: java.lang.ClassNotFoundException: net.gree.unitywebview.CWebViewPlugin

2024/03/27 16:34:49.093 31512 31541 Error Unity 	... 9 more

2024/03/27 16:34:49.093 31512 31541 Error Unity   at UnityEngine.AndroidJNISafe.CheckException () [0x00096] in <0bb982e81108480ab4be62abdda1bf44>:0 

2024/03/27 16:34:49.093 31512 31541 Error Unity   at UnityEngine.AndroidJNISafe.FindClass (System.String name) [0x0000c] in <0bb982e81108480ab4be62abdda1bf44>:0 

2024/03/27 16:34:49.093 31512 31541 Error Unity   at UnityEngine.AndroidJavaObject._An

2020までバージョンを落とした時に正常に動作しているのは確認が取れているのですが2021,2022のLTS環境ではうまく動作しなかったです

**Comment by omochi0619** [comment]
自分がダウンロードした後に修正版が出ていたのを今確認をして再ダウンロードのほうしたところ正常に動作しました
