### ISSUE TITLE
java.lang.NoSuchMethodError in net.gree.unitywebview.CWebViewPlugin$2.onGlobalLayout

### ISSUE THREAD

**Issue by lloydgoodall** [gree/unity-webview#143]
**java.lang.NoSuchMethodError
in net.gree.unitywebview.CWebViewPlugin$2.onGlobalLayout**

My app has gotten a crash report with the following stack trace:

> java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 5.5.0p2
Device model      : PANTECH ADR8995
Device fingerprint: verizon/ADR8995/ADR8995:2.3.3/GRI40/ADR8995_2013_03_13:user/release-keys
Caused by: java.lang.NoSuchMethodError: android.view.Display.getSize
	at net.gree.unitywebview.CWebViewPlugin$2.onGlobalLayout(CWebViewPlugin.java:196)
	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:549)
	at android.view.ViewRoot.performTraversals(ViewRoot.java:1195)
	at android.view.ViewRoot.handleMessage(ViewRoot.java:1867)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:123)
	at android.app.ActivityThread.main(ActivityThread.java:3683)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
	at dalvik.system.NativeStart.main(Native Method)

Device:

> Device
Apache (ADR8995)
Manufacturer Pantech Android version Android 2.3.3 - 2.3.7 RAM (MB) 512 Screen size 800 × 480 Screen density (dpi) 240 OpenGL ES version 2.0 Native platform armeabi-v7a CPU make Qualcomm CPU model MSM8655

**Comment by KojiNakamaru** [comment]
The issue should be fixed in #144 and #145. Could you please try the latest?

**Comment by lloydgoodall** [comment]
Hi,

Thanks for doing this fix, unfortunately I can not test it as I do not have a device that will reproduce the issue.

I only had this info from a crash report from a user.

Thanks,
Lloyd.
