### ISSUE TITLE
当要打开一个没有安装的应用崩溃了

### ISSUE THREAD

**Issue by lwtbn1** [gree/unity-webview#308]
您好，webview里要打开qq钱包支付，但是手机上没有安装qq。然后就闪退了。如下是错误信息。是不是没有做异常处理呢？
658 17784-17784/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.superteam.bzsg.self, PID: 17784
                                                   java.lang.Error: FATAL EXCEPTION [main]
                                                   Unity version     : 2017.3.1p4
                                                   Device model      : HUAWEI HUAWEI NXT-AL10
                                                   Device fingerprint: HUAWEI/NXT-AL10/HWNXT:7.0/HUAWEINXT-AL10/C00B596:user/release-keys
                                                   
                                                   Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=mqqapi://forward/url?src_type=web&style=default&version=1&url_prefix=aHR0cHM6Ly9teXVuLnRlbnBheS5jb20vbXFxL3BheS9xcmNvZGUuaHRtbD9fd3Y9MTAyNyZfYmlkPTIxODMmdD01VjU4ZGM2NDA3OWFiOGM1MTFiZTYzMjM2OTk1ZWRiNQ== }
                                                       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1854)
                                                       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1544)
                                                       at android.app.Activity.startActivityForResult(Activity.java:4391)
                                                       at android.app.Activity.startActivityForResult(Activity.java:4335)
                                                       at android.app.Activity.startActivity(Activity.java:4702)
                                                       at android.app.Activity.startActivity(Activity.java:4670)
                                                       at net.gree.unitywebview.CWebViewPlugin$1$2.shouldOverrideUrlLoading(CWebViewPlugin.java:214)
                                                       at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:73)
                                                       at com.android.webview.chromium.WebViewContentsClientAdapter.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:73)
                                                       at org.chromium.android_webview.AwContentsClient.shouldIgnoreNavigation(AwContentsClient.java:15)
                                                       at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:160)
                                                       at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
                                                       at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
                                                       at android.os.Handler.dispatchMessage(Handler.java:105)
                                                       at android.os.Looper.loop(Looper.java:156)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by lwtbn1** [comment]
This issue only appears on the android platform.

**Comment by KojiNakamaru** [comment]
Thank you for the report. I've fixed the issue in #309 and updated binaries. Could you please try the latest?

**Comment by lwtbn1** [comment]
ok ，i will try it soon。  and  i have a new question，it seems that the webview can not open other app on IOS platform。

**Comment by KojiNakamaru** [comment]
> it seems that the webview can not open other app on IOS platform。need i add some url schema？

Thanks for pointing the issue, I've fixed it in #311 and updated binaries. As you noted, it is also required to add custom url schemes in `LSApplicationQueriesSchemes` in Info.plist.
