### ISSUE TITLE
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference        at net.gree.unitywebview.CWebViewPlugin.<init>(CWebViewPlugin.java:122)

### ISSUE THREAD

**Issue by CurtainNie** [gree/unity-webview#555]
Hi,
We are using this plugin for both android and iOS. We got this below issue from Firebase Console after we upload it. Kindly provide us the solution ASAP.
I got a lot of errors like this

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
       at net.gree.unitywebview.CWebViewPlugin.<init>(CWebViewPlugin.java:122)
       at java.lang.Class.newInstance(Class.java)
       at android.app.Fragment.instantiate(Fragment.java:627)
       at android.app.FragmentState.instantiate(Fragment.java:114)
       at android.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:1880)
       at android.app.FragmentController.restoreAllState(FragmentController.java:123)
       at android.app.Activity.onCreate(Activity.java:1048)
       at com.unity3d.player.UnityPlayerActivity.onCreate()
       at com.google.firebase.MessagingUnityPlayerActivity.onCreate(MessagingUnityPlayerActivity.java:75)
       at android.app.Activity.performCreate(Activity.java:6904)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
       at android.app.ActivityThread.access$1100(ActivityThread.java:229)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

Can you help us fix this problem

**Comment by KojiNakamaru** [comment]
I'm sorry for the error, the issue was reported recently and I've fixed it. Could you please check https://github.com/gree/unity-webview/issues/547#issuecomment-627054288 .
