### ISSUE TITLE
Webview not working on Webgl -  Unity 2020.1.6

### ISSUE THREAD

**Issue by AasiqSA-Personal** [gree/unity-webview#672]
Unity changed the "index.html" template and Loader methods on Unity 2020. unity-webview uses old template and it's not working on newer version. Is there any workaround to make it work for 2020.x versions? Thanks!

Attached templates on unity-webview asset and new minimal webgl templates for reference!
Unity-webview asset template
<img width="759" alt="Screenshot 2021-04-08 at 3 09 34 PM" src="https://user-images.githubusercontent.com/27628549/114004765-977f4880-987c-11eb-9d7c-0ff784402406.png">

Minimal webgl template on 2020.1.6
<img width="773" alt="Screenshot 2021-04-08 at 3 08 24 PM" src="https://user-images.githubusercontent.com/27628549/114005035-cd243180-987c-11eb-9061-95a767e99914.png">

Os: macOS Big Sur 11.2.3
Unity: 2020.1.6f1
Browser: Chrome 89.0.4389.114

**Comment by KojiNakamaru** [comment]
I introduced a new template unity-webview-2020 for 2020.x and updated binaries. Though it is rather experimental one, could you please try it?

**Comment by AasiqSA-Personal** [comment]
Tried it on 2020.1.6f1 and the sample scene is Working! (except the google.com hyperlink. I think it's related to the cross-origin issue you've mentioned in some other thread)

**Comment by SaadAnees** [comment]
Hi, I tried to run this but cant open any link.. Following is the error:

`
Invoking error handler due to
SecurityError: Blocked a frame with origin "https://www.google.com" from accessing a cross-origin frame.
Error: Blocked a frame with origin "https://www.google.com" from accessing a cross-origin frame.
    at Object.evaluateJS (https://www.google.com/Build/unity-webview.js:85:38)
    at __gree_unity_webview_evaluateJS(https://www.google.com/Build/Build/Build.framework.js:2:143131)
    at<anonymous>:wasm - function[31816]:0x8a7c00
    at<anonymous>:wasm - function[31826]:0x8a7df2
    at<anonymous>:wasm - function[31620]:0x892e58
    at<anonymous>:wasm - function[15715]:0x5e3191
    at<anonymous>:wasm - function[16682]:0x612b23
    at<anonymous>:wasm - function[31830]:0x8a7edd
    at<anonymous>:wasm - function[24700]:0x759619
    at dynCall_iiiii(<anonymous>:wasm - function[34311]:0x9156e4)
    at Object.dynCall_iiiii(https://www.google.com/Build/Build/Build.framework.js:2:415442)
    at invoke_iiiii (https://www.google.com/Build/Build/Build.framework.js:2:306117)
    at<anonymous>:wasm-function[32431]:0x8c018a
    at<anonymous>:wasm-function[31877]:0x8a8aef
    at<anonymous>:wasm-function[4219]:0x180b6d
    at<anonymous>:wasm-function[4217]:0x18083d
    at<anonymous>:wasm-function[8176]:0x2e1353
    at<anonymous>:wasm-function[8174]:0x2e0274
    at<anonymous>:wasm-function[11748]:0x46a481
    at _SendMessageString (<anonymous>:wasm-function[10280]:0x3a6590)
    at https://www.google.com/Build/Build/Build.framework.js:2:361603
    at Object.ccall(https://www.google.com/Build/Build/Build.framework.js:2:10403)
    at Object.SendMessage (https://www.google.com/Build/Build/Build.framework.js:2:3105)
    at Object.SendMessage (https://www.google.com/Build/Build/Build.loader.js:1:4926)
    at HTMLIFrameElement.<anonymous> (https://www.google.com/Build/unity-webview.js:46:31)
    at HTMLIFrameElement.dispatch (https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js:3:9922)
    at HTMLIFrameElement.q.handle (https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js:3:7949)`

I deployed it on my site and it has CORS policy enabled. Please help me. Thanks.

**Comment by KojiNakamaru** [comment]
You need to control www.google.com not your site, thus this issue is unavoidable without tweaking browser settings.
cf. https://github.com/gree/unity-webview/issues/507
cf. https://github.com/gree/unity-webview/issues/613#issuecomment-755008489

**Comment by Daniel-Tigreros-Teys** [comment]
Hello KojiNakamaru, sorry for the question but, whats mean that you need to control google.com, Im trying the same with others webpage and have the same problem. Thanks

**Comment by KojiNakamaru** [comment]
It means "impossible" basically. If you can tweak the target site so that its response has an adequate Access-Control-Allow-Origin header (cf. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin ), you can overcome  the restriction.
